if(true)
{var back_url='';if(_get('visit_id')){var visit_id=_get('visit_id');setCookie('ws_visit_id',visit_id,0,'/',null,false);}else{var visit_id=getCookie('ws_visit_id');if(visit_id==''){visit_id=get_visit_id();setCookie('ws_visit_id',visit_id,0,'/',null,false);}else{back_url=escape(encodeURI(document.referrer));}}
if(_get('customer_id')){var customer_id=_get('customer_id');setCookie('ws_customer_id',customer_id,10*365*24*3600*1000,'/',null,false);}else{var customer_id=getCookie('ws_customer_id');if(customer_id==''){customer_id=visit_id;setCookie('ws_customer_id',customer_id,10*365*24*3600*1000,'/',null,false);}}
if(_get('prom_id')){var prom_id=_get('prom_id');setCookie('ws_prom_id',prom_id,0,'/',null,false);}else{var prom_id=getCookie('ws_prom_id');if(!prom_id){prom_id=get_prom_id(window.location.href);prom_id=prom_id?prom_id:'0';setCookie('ws_prom_id',prom_id,0,'/',null,false);}}
var ref_url=getCookie('ws_referer_url')?getCookie('ws_referer_url'):getCookie('first_ref_url');if(ref_url===''){ref_url=get_referer_url();setCookie('ws_referer_url',ref_url,0,'/',null,false);if(getCookie('first_ref_url')==='')setCookie('first_ref_url',ref_url,10*365*24*3600*1000,'/',null,false);}
var this_url=escape(encodeURI(window.location.href));var brand_url=get_brand_url();var height=screen.height;var width=screen.width;var cookie=0;var frame=0;var java=0;var javas=0;document.cookie="CbsCookieName=value";var arrStr=document.cookie.split("; ");for(var i=0;i<arrStr.length;i++){var temp=arrStr[i].split("=");if(temp[0]=='CbsCookieName'){cookie=1;}}
if(self!=top)frame='1';if(navigator.appName.substring(0,2)=="Mi")java='1';javas=cookie+","+frame+","+java;var url_header=('https:'==document.location.protocol?'https://':'http://');var url=url_header+brand_url+"/go.php?track=visit";url+="&visit_id="+visit_id+"&customer_id="+customer_id+"&prom_id="+prom_id;url+="&height="+height+"&width="+width+"&javas="+javas+"&ref_url="+ref_url;var src_path=url+"&this_url="+this_url+"&back_url="+back_url;document.write("<div id='track_div' style='display:none'><iframe id='cbs_track_frame' src='"+src_path+"'></iframe></div>");document.onmousedown=function(e){var href_str;var more_download_url;var evt=e||event;var obj=evt.srcElement||evt.target;var o=findA(obj);if(o){href_str=o.href;if(href_str.substr(0,4)=="http"&&href_str.substr(0,10)!="http://cbs"){if(href_str.indexOf("swreg.org")!=-1){var pos=href_str.indexOf('&a=');if(pos>-1){href_str=href_str.substring(0,pos+3)+visit_id;}else{href_str=href_str+'&a='+visit_id;}
o.setAttribute('target','_blank');simulate_buy_path(url,href_str,this_url);}else if(href_str.indexOf("regnow.com")!=-1){if(window.location.host.indexOf('spotmau.com')>-1&&href_str.indexOf('&linkid=')>-1){}else{if(href_str.indexOf("?")<0){href_str=href_str+'?';}
var pos=href_str.indexOf('&linkid=');if(pos>-1){href_str=href_str.substring(0,pos+8)+visit_id;}else{href_str=href_str+'&linkid='+visit_id;}}
o.setAttribute('target','_blank');simulate_buy_path(url,href_str,this_url);}else if(href_str.indexOf('shareit.com')!=-1){var additionalStr='&HADD['+href_str.match(/\[(\d+)\]/i)[1]+'][ADDITIONAL1]=';var pos=href_str.indexOf(additionalStr);if(pos>-1){href_str=href_str.substring(0,pos+additionalStr.length)+visit_id;}else{href_str=href_str+additionalStr+visit_id;}
o.setAttribute('target','_blank');simulate_buy_path(url,href_str,this_url);}else if(href_str.indexOf('store.')!=-1&&href_str.indexOf('.com')!=-1&&href_str.indexOf('store.')<href_str.indexOf('.com')&&window.location.href.indexOf('store.')==-1&&window.location.href.indexOf('wondershare.com')==-1||href_str.indexOf('store.')!=-1&&href_str.indexOf('.jp')!=-1&&href_str.indexOf('store.')<href_str.indexOf('.jp')){if(href_str.indexOf('index.php')!=-1){var pos=href_str.indexOf('&visit_id=');if(pos>-1){href_str=href_str.substring(0,pos+10)+visit_id;}else{href_str=href_str+'&visit_id='+visit_id;}}
simulate_buy_path(url,href_str,this_url);}else if(href_str.indexOf('avangate.com')!=-1){var pos=href_str.indexOf('&REF=');if(pos>-1){href_str=href_str.substring(0,pos+5)+"visit_id-"+visit_id;}else{href_str=href_str+'&REF='+"visit_id-"+visit_id;}
simulate_buy_path(url,href_str,this_url);}else if(href_str.toLowerCase().indexOf('.exe')>-1||href_str.toLowerCase().indexOf('.dmg')>-1||href_str.toLowerCase().indexOf('.zip')>-1){simulate_buy_path(url,href_str,this_url);}
o.href=href_str;return true;}else if(href_str.indexOf('paypal.php')!=-1){var msg="PayPal system is being maintained!\n\n";msg+="Dear customer, thanks for your interest in our products.\n";msg+="Please try the alternative order link temporarily. Wish you happy shopping!\n";alert(msg);return false;}}}}
function findA(obj)
{if(obj==document.body||obj.tagName=="HTML"||obj.tagName=="BODY"||obj=="undefined"){return null;}else if(obj.tagName=="A"){return obj;}
obj=obj.parentNode;return arguments.callee(obj);}
function get_brand_url(){var sArr=document.getElementsByTagName("SCRIPT");var pids="";var rs;for(var i=0;i<sArr.length;i++){rs="";if(sArr[i].src.indexOf("//cbs.")!=-1&&sArr[i].src.indexOf("/jslibs/")!=-1){rs=sArr[i].src.split('/');return rs[2];}}
if(!rs){return"cbs.wondershare.com"}}
function get_visit_id(){var date=new Date();var y=date.getFullYear().toString().substr(2,2);var m=date.getMonth()+1;var d=date.getDate();var h=date.getHours();var i=date.getMinutes();var s=date.getSeconds();var ms=date.getMilliseconds();var _random=Math.round(Math.random()*Math.random()*10000);var random_len=_random.toString().length;if(random_len==1){_random=_random+'000';}else if(random_len==2){_random=_random+'00';}else if(random_len==3){_random=_random+'0';}
var visit_id=y;visit_id+=m<10?'0'+m:m;visit_id+=d<10?'0'+d:d;visit_id+=h<10?'0'+h:h;visit_id+=i<10?'0'+i:i;visit_id+=s<10?'0'+s:s;if(ms<10){visit_id+='00'+ms;}else if(ms<100){visit_id+='0'+ms;}else{visit_id+=ms;}
visit_id+='_'+_random;return visit_id;}
function get_referer_url(){var ref_url=document.referrer;var this_url=document.location.href;if(this_url.indexOf('gwd=')>-1){ref_url+='#gwd_url='+this_url;}
ref_url=ref_url?ref_url:'null';return escape(encodeURI(ref_url));}
function get_prom_id(url){var prom_id='';var reg=new RegExp(/^.+(page=|#)([0-9]+)(.*)$/);if(url.indexOf('forum')==-1&&reg.exec(url)&&reg.exec(url)[2]>100){prom_id=reg.exec(url)[2];}else if(url.indexOf('smid=')>-1){var pos_1=url.indexOf('smid=');var temp_str=url.substring(pos_1,url.length);var pos_2=temp_str.indexOf('&');if(pos_2>-1){prom_id=temp_str.substring(5,pos_2);}else{prom_id=temp_str.substring(5,temp_str.length);}
prom_id='sm'+prom_id;}
return prom_id;}
function setCookie(name,value,time,path,domain,secure){var exp=new Date();exp.setTime(exp.getTime()+parseInt(time));var expiryString=time?";expires="+exp.toGMTString():'';var pathString=(path==null)?"":" ;path = "+path;var domainString=(domain==null)?"":" ;domain = "+domain;var secureString=(secure)?";secure":"";document.cookie=name+"="+escape(value)+expiryString+pathString+domainString+secureString;}
function getCookie(name){var CookieFound=false;var start=0;var end=0;var CookieString=document.cookie;var i=0;while(i<=CookieString.length){start=i;end=start+name.length;if(CookieString.substring(start,end)==name){CookieFound=true;break;}
i++;}
if(CookieFound){start=end+1;end=CookieString.indexOf(";",start);if(end<start)end=CookieString.length;return unescape(CookieString.substring(start,end));}
return"";}
function _get(name){var arr={};var query_str=location.search;var temp1=query_str.substr(1).split('&');for(var i in temp1){var temp2=temp1[i].split('=');arr[temp2[0]]=temp2[1];}
return arr[name];}
function is_mouse_leftKey(e){var is_ie=navigator.userAgent.toLowerCase().indexOf('msie')>-1?1:0;var evt=e||event;var res;if(is_ie){res=evt.button==1?1:0;}else{res=evt.button==0?1:0;}
return res;}
function simulate_buy_path(base_url,this_url,back_url){var url=base_url+'&this_url='+encodeURIComponent(this_url);url+='&back_url='+encodeURIComponent(back_url);if(document.images){img=new Image;img.onerror=(img.onload=(img.onabort=function(){delete img;}));img.src=url+'&uuid='+new Date().getTime();}
return true;}